### ISSUE TITLE
Incompatible with PingDisplay

### ISSUE THREAD

**Issue by DeathWrench** [Confusified/LC-InsanityDisplay#3]
**Mod (please complete the following information):**
- Version: 1.1.1

**Game (please complete the following information):**
- Version: v49

**Describe the bug**
[PingDisplay](https://thunderstore.io/c/lethal-company/p/DeathWrench/PingDisplay/) incompatibility. The mods fail to work if both are installed it seems.

**To Reproduce**
Install [InsanityDisplay](https://thunderstore.io/c/lethal-company/p/Confusified/InsanityDisplay/) and [PingDisplay](https://thunderstore.io/c/lethal-company/p/DeathWrench/PingDisplay/)

**Expected behavior**
Both mods working at the same time.

**Comment by Confusified** [comment]
hey so i've looked into it and i don't think InsanityDisplay has anything to do with it

it seems to be PingDisplay itself, it works fine on version 1.3.0 but version 1.3.1 doesn't

**Comment by Confusified** [comment]
i made a pull request to fix it

**Comment by DeathWrench** [comment]
Still happens for me. Here's the profile code if you want to try to reproduce: ```018eca71-a267-c6ff-741b-c14b284d9bfe```

**Comment by Confusified** [comment]
have you updated the mod with the code changes? i think it's still using the broken one

**Comment by DeathWrench** [comment]
Not yet, after testing it on my end, the issue still occurs. The one on Thunderstore is spamming errors when both are installed for me, I figure might also help with troubleshooting. https://github.com/DeathWrench/PingDisplay/commit/54337e8f6fa83565f42d576c95a665ce91237cd1

**Comment by Confusified** [comment]
does the issue occur when using the updated version (the one that isn't on thunderstore yet)?

**Comment by DeathWrench** [comment]
> does the issue occur when using the updated version (the one that isn't on thunderstore yet)?

If both mods are installed they both fail to work, changing Start to Awake did not help.
If I revert https://github.com/DeathWrench/PingDisplay/commit/54337e8f6fa83565f42d576c95a665ce91237cd1 and install both mods this error gets spammed:
```
[02:54:49.1573388] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
PingDisplay.Plugin+HudManagerPatch.PatchHudManagerUpdate (HUDManager& __instance) (at <f36624c7dd0f403c802e3fa5e7546f68>:IL_0025)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::Update>(HUDManager)
```

**Comment by Confusified** [comment]
i won't be able to do anything this weekend so i'll try to debug it next week

**Comment by Confusified** [comment]
i haven't been able to reproduce the same issue but i tried to make some changes to hopefully fix it anyway
[PingDisplay-1.3.2-edited.zip](https://github.com/Confusified/LC-InsanityDisplay/files/14971993/PingDisplay-1.3.2-edited.zip)
i added a zip file which has the dll with the changes so you don't have to build it yourself, i'll also be making a pull request for the changes i made
