### ISSUE TITLE
GeneralImprovements Compatability

### ISSUE THREAD

**Issue by ghost** [Confusified/LC-InsanityDisplay#4]
Would love to see [GeneralImprovements](https://thunderstore.io/c/lethal-company/p/ShaosilGaming/GeneralImprovements/) HP overlay compatability! It works however there is slight overlap.

![image](https://github.com/Confusified/LC-InsanityDisplay/assets/90943643/144cd2c0-6cb7-490c-8a3b-30ccfd160fdf)

**Comment by Confusified** [comment]
oh yes i'll be sure to add compatibility for that
